// Code generated by Slice Machine. DO NOT EDIT.

import CardList from './CardList/index.svelte';
import ContactForm from './ContactForm/index.svelte';
import HeroText from './HeroText/index.svelte';
import RichText from './RichText/index.svelte';

export const components = {
	card_list: CardList,
	contact_form: ContactForm,
	hero_text: HeroText,
	rich_text: RichText
};
