// Code generated by Slice Machine. DO NOT EDIT.

import HeroText from './HeroText/index.svelte';
import RichText from './RichText/index.svelte';

export const components = {
	hero_text: HeroText,
	rich_text: RichText
};
